exports.BOOKING_NOT_PAID = 'BOOKING_NOT_PAID';
exports.BOOKING_CANCEL = 'BOOKING_CANCEL';
exports.BOOKING_SUCCESS = 'BOOKING_SUCCESS';

exports.STADIUM_OPEN = 'STADIUM_OPEN';
exports.STADIUM_CLOSE = 'STADIUM_CLOSE';
